// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXe6FCUsCNybSAp5aNNp4yb6qerJ1F6ow',
    appId: '1:1054458323047:web:e694e1efaf20c47ddcf4c2',
    messagingSenderId: '1054458323047',
    projectId: 'parkinson-hero',
    authDomain: 'parkinson-hero.firebaseapp.com',
    storageBucket: 'parkinson-hero.firebasestorage.app',
    measurementId: 'G-VMG6LDEBPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQYcZGDPvjrbsfqdIcC48MzV87pHSaZ9U',
    appId: '1:1054458323047:android:11b801361fb0bd79dcf4c2',
    messagingSenderId: '1054458323047',
    projectId: 'parkinson-hero',
    storageBucket: 'parkinson-hero.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCigxx9jGZ63nSpNwi-SMayuIZSGNSy8M',
    appId: '1:1054458323047:ios:d70aa4e8ca44a838dcf4c2',
    messagingSenderId: '1054458323047',
    projectId: 'parkinson-hero',
    storageBucket: 'parkinson-hero.firebasestorage.app',
    iosBundleId: 'com.example.parkinsonHero',
  );

}